---
- name: Create docker group
  hosts: all
  become: yes
  become_user: root

  tasks:
    - name: Create docker group
      group:
        name: docker
        state: present

    - name: Add user to the docker group
      user:
        name: "{{ item }}"
        groups: docker
        append: yes
      with_items: "{{ ansible_user }}"
