---
- name: Install Oh My Zsh and set default shell
  hosts: localhost
  become: yes
  tasks:
    - name: Install Zsh
      apt:
        name: zsh
        state: present

    - name: Change default shell to Zsh
      command: chsh -s /bin/zsh "{{ ansible_user }}"

    - name: Install git
      apt:
        name: git
        state: present

    - name: Clone Oh My Zsh repository
      git:
        repo: https://github.com/ohmyzsh/ohmyzsh.git
        dest: ~/.oh-my-zsh
        clone: yes

    - name: Copy Oh My Zsh config
      command: cp ~/.oh-my-zsh/templates/zshrc.zsh-template ~/.zshrc
      args:
        creates: ~/.zshrc
