---
- hosts: all
  become: yes
  tasks:
    - name: Installing tmux dependencies
      apt:
        name: "{{ item }}"
        update_cache: yes
      loop:
        - curl
    
    - name: Run autogen.sh
      ansible.builtin.shell: cd /tmp && curl -LOJ https://github.com/the-via/releases/releases/download/v3.0.0/via-3.0.0-linux.deb
      args:
        executable: /bin/bash
      become: true

    - name: Run configure
      ansible.builtin.shell: cd /tmp && sudo apt install -y ./via-3.0.0-linux.deb
      args:
        executable: /bin/bash
      become: true
